version: "3.3"
name: scso-mt

services:
  dev:
    image: nvidia/cuda:12.3.2-devel-ubuntu22.04
    container_name: scso-mt-dev
    # runtime: nvidia
    build: .
    ports:
      - 8887:8887
      - 8888:8888
      - 22700:22700
      - 8896:8896
      - 6006:6006
    tty: true
    privileged: true
    volumes:
      - $PWD:/home/code-base/runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
