FROM jetpack-sdk-host:5.1.2

# jetpack 5.1.2 has both nsys-ui 2022.3.1 and 2023.2.4 installed
# we will use 2023.2.4
RUN sudo update-alternatives --set nsys-ui /opt/nvidia/nsight-systems/2023.2.4/host-linux-x64/nsys-ui

